---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true
  #use_sudo: false
  #privileged: true #required for elasticsearch init script to complete successfully

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list: ['ectg-iptables::sshd-world', 'ectg-iptables::sshd', 'ectg-iptables::elasticsearch']